Document: workspaces-material-shell
Title: Debian workspaces-material-shell Manual
Author: <insert document author here>
Abstract: This manual describes what workspaces-material-shell is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/workspaces-material-shell/workspaces-material-shell.sgml.gz

Format: postscript
Files: /usr/share/doc/workspaces-material-shell/workspaces-material-shell.ps.gz

Format: text
Files: /usr/share/doc/workspaces-material-shell/workspaces-material-shell.text.gz

Format: HTML
Index: /usr/share/doc/workspaces-material-shell/html/index.html
Files: /usr/share/doc/workspaces-material-shell/html/*.html
